/**
 * @deprecated
 * 請使用 vehicleList 取代
 */
export const carTypeList = [
  {
    id: "1",
    name: "EX40",
    img: new URL("@/assets/img/EX40.png", import.meta.url).href,
    mainCategory: "電動",
    type: "休旅車",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
  {
    id: "3",
    name: "EX30",
    img: new URL("@/assets/img/EX30.png", import.meta.url).href,
    mainCategory: "電動",
    type: "休旅車",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
  {
    id: "2",
    name: "EC40",
    img: new URL("@/assets/img/EC40.png", import.meta.url).href,
    mainCategory: "電動",
    type: "跨界跑旅",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
  {
    id: "6",
    name: "XC90",
    img: new URL("@/assets/img/XC90.png", import.meta.url).href,
    mainCategory: "雙能電動",
    type: "休旅車",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
  {
    id: "9",
    name: "XC60",
    img: new URL("@/assets/img/XC60.png", import.meta.url).href,
    mainCategory: "雙能電動",
    type: "休旅車",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
  {
    id: "7",
    name: "V60",
    img: new URL("@/assets/img/V60.png", import.meta.url).href,
    mainCategory: "雙能電動",
    type: "旅行車",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
  {
    id: "8",
    name: "XC40",
    img: new URL("@/assets/img/XC40.png", import.meta.url).href,
    mainCategory: "高效輕油電",
    type: "休旅車",
    modelId: "",
    modelCode: "",
    modelName: "",
  },
];
